# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d78237d7d9030e2d815b48120faae84014f75579d80eb4b02e065a3957da53831377f2aa749543deb76ce9c302cd77501cc8334b3a3de382337f0d2b001f42f5

test:
  secret_key_base: fb23df2bc8610006e8ac5453d2e5930179e2dd2afb0da1453283e1ebc13fe23b1db751a5de4d5e663f6b30f719e2002f4065f4638772c76b76d9efbc36c64fcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
